include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    todo: ignore

linter:

  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_specify_types: true
    avoid_dynamic_calls: true
    avoid_redundant_argument_values: true
    avoid_print: true
    prefer_single_quotes: true
    # flutter_style_todos: true TODO(dnfield): enable this eventually
    hash_and_equals: true
    no_default_cases: true
    only_throw_errors: true
    prefer_final_fields: true
    prefer_final_locals: true
    public_member_api_docs: true
    recursive_getters: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    unnecessary_late: true
