name: vector_graphics
description: A vector graphics rendering package for Flutter.
version: 1.1.10
homepage: https://github.com/dnfield/vector_graphics

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.5.0-0"

dependencies:
  flutter:
    sdk: flutter
  vector_graphics_codec: 1.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  vector_graphics_compiler: 1.1.10

# Comment out before publishing
dependency_overrides:
  vector_graphics_codec:
    path: ../vector_graphics_codec
  vector_graphics_compiler:
    path: ../vector_graphics_compiler

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
