// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:convert';
import 'dart:developer';

import 'package:http/http.dart' as http;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:vector_graphics/vector_graphics.dart';
import 'package:vector_graphics_compiler/vector_graphics_compiler.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Vector Graphics Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Scaffold(
        body: Center(
          child: VectorGraphic(
            loader: MemBytesLoader(),
            // loader: NetworkSvgLoader(
            //   'https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg',
            // ),
          ),
        ),
      ),
    );
  }
}

class MemBytesLoader extends BytesLoader {
  const MemBytesLoader();

  static const String b64 =
  'Yi2IAAEpAACWRAAAr0Md/wAA/wAAAwAAgEAAAIA/AAD//xz/AAD/AwEA//8cAAD//wMCAP//HAAA/8wDAwD//xwAAP+ZAwQA//8cAAD/ZgMFAP//HAAA/zMDBgD//xwAgAD/AwcA//8cAAD/vwMIAP//HACAAL8DCQD//xwAAP9/AwoA//8cAIAAfwMLAP//HAAA/z8DDAD//xwAgAA/Aw0A//8bAAAABQAAAAABAQEDCAAAAAAAAAAAgD8AAIA/AOCVRAAAgD8A4JVEAICuQwAAgD8AgK5DGwEBAAkAAAAAAQEBAQECAgMYAAAAAAAAAAAWQwAAyEIAAMhCAADIQgAAyEIAAHpDAICJRAAAekMAgIlEAADIQgAAekMAAMhCAAB6QwYx/0KDmGNDAAAWQwAASEMAABZDfWcsQwAAFkMAABZDBjH/QgAAFkMAAMhCGwECAAYAAAAAAgICAgMaAAAAAAAAAEhDAABIQoOYY0MAAEhCAAB6Q/rOkEIAAHpDAADIQgAAekMGMf9Cg5hjQwAAFkMAAEhDAAAWQ31nLEMAABZDAAAWQwYx/0IAABZDAADIQgAAFkP6zpBCfWcsQwAASEIAAEhDAABIQhsBAwAGAAAAAAICAgIDGgAAAAAAAADIQwAASEJCzNVDAABIQgAA4UP6zpBCAADhQwAAyEIAAOFDBjH/QkLM1UMAABZDAADIQwAAFkO+M7pDAAAWQwAAr0MGMf9CAACvQwAAyEIAAK9D+s6QQr4zukMAAEhCAADIQwAASEIbAQQABgAAAAACAgICAxoAAAAAAAAAFkQAAEhCIeYcRAAASEIAgCJE+s6QQgCAIkQAAMhCAIAiRAYx/0Ih5hxEAAAWQwAAFkQAABZD3xkPRAAAFkMAgAlEBjH/QgCACUQAAMhCAIAJRPrOkELfGQ9EAABIQgAAFkQAAEhCGwEFAAYAAAAAAgICAgMaAAAAAAAAAEhEAABIQiHmTkQAAEhCAIBURPrOkEIAgFREAADIQgCAVEQGMf9CIeZORAAAFkMAAEhEAAAWQ98ZQUQAABZDAIA7RAYx/0IAgDtEAADIQgCAO0T6zpBC3xlBRAAASEIAAEhEAABIQhsBBgAGAAAAAAICAgIDGgAAAAAAAAB6RAAASEIQc4BEAABIQgBAg0T6zpBCAECDRAAAyEIAQINEBjH/QhBzgEQAABZDAAB6RAAAFkPfGXNEAAAWQwCAbUQGMf9CAIBtRAAAyEIAgG1E+s6QQt8Zc0QAAEhCAAB6RAAASEIbAQcACAAAAAACAgICAgIDJgAAAAMASEMrJ0tDZo1CQ1sdSUPDpzxDAABIQwCANkMAAEhDfecaQwAASEMAgARDfWdeQwCABEMAAHpDAIAEQ0LMikN95xpDAACWQwCANkMAAJZDwac8QwAAlkNkjUJDUnGVQwAASENrbJRDNwY1Q6DfkEMAgCdDYbiHQwCAJ0MAAHpDAIAnQz6PZEM3BjVDwEBSQwMASEMrJ0tDGwEIAAYAAAAAAgICAgMaAAAAAAAAgFlDAABIQ4MYdUMAAEhDAMCFQ31nXkMAwIVDAAB6QwDAhUNCzIpDgxh1QwAAlkMAgFlDAACWQ33nPUMAAJZDAIAnQ0LMikMAgCdDAAB6QwCAJ0N9Z15Dfec9QwAASEMAgFlDAABIQxsBCQAGAAAAAAICAgIDGgAAAAAAAEC/QwAASENCDM1DAABIQwBA2EN9Z15DAEDYQwAAekMAQNhDQsyKQ0IMzUMAAJZDAEC/QwAAlkO+c7FDAACWQwBApkNCzIpDAECmQwAAekMAQKZDfWdeQ75zsUMAAEhDAEC/QwAASEMbAQoABgAAAAACAgICAxoAAAAAAADA0EMAAEhDQozeQwAASEMAwOlDfWdeQwDA6UMAAHpDAMDpQ0LMikNCjN5DAACWQwDA0EMAAJZDvvPCQwAAlkMAwLdDQsyKQwDAt0MAAHpDAMC3Q31nXkO+88JDAABIQwDA0EMAAEhDGwELAAYAAAAAAgICAgMaAAAAAAAAoBFEAABIQyGGGEQAAEhDACAeRH1nXkMAIB5EAAB6QwAgHkRCzIpDIYYYRAAAlkMAoBFEAACWQ9+5CkQAAJZDACAFRELMikMAIAVEAAB6QwAgBUR9Z15D37kKRAAASEMAoBFEAABIQxsBDAAGAAAAAAICAgIDGgAAAAAAAGAaRAAASEMhRiFEAABIQwDgJkR9Z15DAOAmRAAAekMA4CZEQsyKQyFGIUQAAJZDAGAaRAAAlkPfeRNEAACWQwDgDURCzIpDAOANRAAAekMA4A1EfWdeQ995E0QAAEhDAGAaRAAASEMbAQ0ABgAAAAACAgICAxoAAAAAAABgTEQAAEhDIUZTRAAASEMA4FhEfWdeQwDgWEQAAHpDAOBYRELMikMhRlNEAACWQwBgTEQAAJZD33lFRAAAlkMA4D9EQsyKQwDgP0QAAHpDAOA/RH1nXkPfeUVEAABIQwBgTEQAAEhDGwEOAAYAAAAAAgICAgMaAAAAAAAAoENEAABIQyGGSkQAAEhDACBQRH1nXkMAIFBEAAB6QwAgUERCzIpDIYZKRAAAlkMAoENEAACWQ9+5PEQAAJZDACA3RELMikMAIDdEAAB6QwAgN0R9Z15D37k8RAAASEMAoENEAABIQxsBDwAGAAAAAAICAgIDGgAAAAAAAKB1RAAASEMhhnxEAABIQwAQgUR9Z15DABCBRAAAekMAEIFEQsyKQyGGfEQAAJZDAKB1RAAAlkPfuW5EAACWQwAgaURCzIpDACBpRAAAekMAIGlEfWdeQ9+5bkQAAEhDAKB1RAAASEMbABAABgAAAAACAgICAxoAAAAAAABgfkQAAEhDEKOCRAAASEMAcIVEfWdeQwBwhUQAAHpDAHCFRELMikMQo4JEAACWQwBgfkQAAJZD33l3RAAAlkMA4HFEQsyKQwDgcUQAAHpDAOBxRH1nXkPfeXdEAABIQwBgfkQAAEhDMB4AAAAA//8eAQABAP//HgIAAgD//x4DAAMA//8eBAAEAP//HgUABQD//x4GAAYA//8eBwACAP//HggABwD//x4JAAgA//8eCgAJAP//HgsACgD//x4MAAsA//8eDQALAP//Hg4ACgD//x4PAAwA//8eEAANAP//';
      // 'Yi2IAAEpAICQQwAABEQcAAAA/wMAAP//HODc2v8DAQD//x3g3Nr/AAADAACAQAqAcUACAP//HP////8DAwD//xsBAAAMAAAAAAEBAQEDAAEBAQEDFAAAAPS9MEIxaOhDYpB0QzFo6ENikHRD4ByAQvS9MELgHIBC9L0wQjFo6EMHXzdCoCrnQ7wUckOgKudDvBRyQ31ug0IHXzdCfW6DQgdfN0KgKudDGwABAAIAAAAAAQQAAAAAACObz0IAsPBDsPI4QwCw8EMbAAIACgAAAAABAgECAQIBAgMiAAAAAAAAgKxBAAAAAACYhUMAAAAASYuLQwAAAAAAYJBD3ZYaQQBgkEMAgKxBAGCQQwA4/UMAYJBDpZUBREmLi0MAAAREAJiFQwAABEQAgKxBAAAERN2WGkEAAAREAAAAAKWVAUQAAAAAADj9QwAAAAAAgKxBAAAAAN2WGkHdlhpBAAAAAACArEEAAAAAMCUAAB4AAAEA//8eAQACAP//Kx4CAAMA//8mJg==';
   // 'Yi2IAAEpAICQQwAABEQcAAAA/wMAAP//HODc2v8DAQD//x308/H/AAADAACAQAqAcUACAP//HeDc2v8AAAMAAIBACoBxQAMA//8dxsG9/wAAAwAAgED2fyxABAD//xz/////AwUA//8cU6g0/wMGAP//HDVD6v8DBwD//xwFvPv/AwgA//8c9IVC/wMJAP//GwEAAAYAAAAAAQEBAQMKAAAAAABikHRDMWjoQ/S9MEIxaOhD9L0wQuAcgEJikHRD4ByAQmKQdEMxaOhDGwABAAIAAAAAAQQAAAAAACObz0Kr/j1CsPI4Q6v+PUIbAAIAAgAAAAABBAAAAAAAI5vPQgCw8EOw8jhDALDwQxsBAwALAAAAAAECAQIBAgECAQMkAAAAADMTGEPP9/hDrUmGQs/3+EMklzxCz/f4QwCA90Gm6/BDAID3QVb+5kMAgPdBlcWFQgCA90HfIDxCJJc8QgCA90GtSYZCAID3QSObXUMAgPdBHZpxQwCA90EQ6IBD3yA8QhDogEOVxYVCEOiAQ1b+5kMQ6IBDpuvwQx2acUPP9/hDI5tdQ8/3+EMzExhDz/f4QxsBBAAFAAAAAAICAgIaAAAAAAAAj0ScQpFPQUKPRJxCE6FIQlBNmUIOj05Cw6SVQg6PTkI2/JFCDo9OQgUFj0IToUhCBQWPQpFPQUIFBY9Cd/45Qjb8kUL5DzRCw6SVQvkPNEJQTZlC+Q80Qo9EnEJ3/jlCj0ScQpFPQUIbAAUACgAAAAABAgECAQIBAgMiAAAAAAAAgKxBAAAAAACYhUMAAAAASYuLQwAAAAAAYJBD3ZYaQQBgkEMAgKxBAGCQQwA4/UMAYJBDpZUBREmLi0MAAAREAJiFQwAABEQAgKxBAAAERN2WGkEAAAREAAAAAKWVAUQAAAAAADj9QwAAAAAAgKxBAAAAAN2WGkHdlhpBAAAAAACArEEAAAAAGwEGAAYAAAAAAgICAgMaAAAAAAACKyZDAAB1Q9sZKEMAAHVDAqspQ9luc0MCqylDAIBxQwKrKUMnkW9D2xkoQwAAbkMCKyZDAABuQyk8JEMAAG5DAqsiQyeRb0MCqyJDAIBxQwKrIkPZbnNDKTwkQwAAdUMCKyZDAAB1QxsBBwAGAAAAAAICAgIDGgAAAAAAAqsbQz9VgEO0iB9DP1WAQwKrIkMxiH1DAqsiQ3+qeUMCqyJDzcx1Q7SIH0N/qnJDAqsbQ3+qckNQzRdDf6pyQwKrFEPNzHVDAqsUQ3+qeUMCqxRDMYh9Q1DNF0M/VYBDAqsbQz9VgEMbAQgABgAAAAACAgICAxoAAAAAAMGqG0OgqolDUC0gQ6CqiUM/1SNDqNaHQz/VI0NglYVDP9UjQ/hTg0NQLSBDAICBQ8GqG0MAgIFD8CcXQwCAgUMAgBND+FODQwCAE0NglYVDAIATQ6jWh0PwJxdDoKqJQ8GqG0OgqolDGwAJAAYAAAAAAgICAgMaAAAAAACBVQRDP1WAQ+UQDEM/VYBDgVUSQ+NlekOBVRJDf6pyQ4FVEkMb72pD5RAMQ3+qZEOBVQRDf6pkQzk0+UJ/qmRDAqvsQhvvakMCq+xCf6pyQwKr7ELjZXpDOTT5Qj9VgEOBVQRDP1WAQzAlAAAeAAABAP//HgEAAgD//x4CAAMA//8eAwAEAP//HgQAAQD//yseBQAFAP//JiYeBgAGAP//HgcABwD//x4IAAgA//8eCQAJAP//';

  @override
  Future<ByteData> loadBytes(BuildContext? context) async {
    return base64Decode(b64).buffer.asByteData();
  }
}

class NetworkSvgLoader extends BytesLoader {
  const NetworkSvgLoader(this.url);

  final String url;

  @override
  Future<ByteData> loadBytes(BuildContext? context) async {
    return await compute((String svgUrl) async {
      final http.Response request = await http.get(Uri.parse(svgUrl));
      final TimelineTask task = TimelineTask()..start('encodeSvg');
      final Uint8List compiledBytes = encodeSvg(
        xml: request.body,
        debugName: svgUrl,
        enableClippingOptimizer: false,
        enableMaskingOptimizer: false,
        enableOverdrawOptimizer: false,
      );
      task.finish();
      // sendAndExit will make sure this isn't copied.
      return compiledBytes.buffer.asByteData();
    }, url, debugLabel: 'Load Bytes');
  }

  @override
  int get hashCode => url.hashCode;

  @override
  bool operator ==(Object other) {
    return other is NetworkSvgLoader && other.url == url;
  }
}
