name: example
description: An example of the vector_graphics package
publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: 0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/bars.bin
    - assets/tiger.bin # ghostscript tiger


# Comment out before publishing
dependency_overrides:
  vector_graphics_codec:
    path: ../../vector_graphics_codec
  vector_graphics:
    path: ../
