name: vector_graphics_codec
description: An encoding library for `package:vector_graphics`
version: 1.1.5
homepage: https://github.com/dnfield/vector_graphics

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
