name: vector_graphics_codec
description: An encoding library for `package:vector_graphics`
version: 0.0.2
homepage: https://github.com/dnfield/vector_graphics

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.20.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
